// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7BmtCka9QdmM2uDeDeqOaqRBpMGB5lDY',
    appId: '1:216432343824:web:b32ff63c744c2b05bcc395',
    messagingSenderId: '216432343824',
    projectId: 'keri-shipper',
    authDomain: 'keri-shipper.firebaseapp.com',
    storageBucket: 'keri-shipper.appspot.com',
    measurementId: 'G-YS548Q9336',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5uELyBqC-410A8UvwN9OZMyLJhCllGeQ',
    appId: '1:216432343824:android:818676d83cff94f2bcc395',
    messagingSenderId: '216432343824',
    projectId: 'keri-shipper',
    storageBucket: 'keri-shipper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBixkIv8rg7htyDcKJh2Avnl_LfEYbL-iA',
    appId: '1:216432343824:ios:01a7a72d1ec732eabcc395',
    messagingSenderId: '216432343824',
    projectId: 'keri-shipper',
    storageBucket: 'keri-shipper.appspot.com',
    iosBundleId: 'com.example.keriShipper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBixkIv8rg7htyDcKJh2Avnl_LfEYbL-iA',
    appId: '1:216432343824:ios:f1fe2ac95ef20df0bcc395',
    messagingSenderId: '216432343824',
    projectId: 'keri-shipper',
    storageBucket: 'keri-shipper.appspot.com',
    iosBundleId: 'com.example.keriShipper.RunnerTests',
  );
}
